# Generated by Django 3.2.9 on 2021-12-28 10:03

import Subscrap.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Subscrap', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sublist',
            name='cost',
            field=models.FloatField(default=0, validators=[Subscrap.models.validate_postive]),
        ),
        migrations.AlterField(
            model_name='sublist',
            name='startDate',
            field=models.DateField(default=datetime.datetime(2021, 12, 28, 10, 3, 30, 314204)),
        ),
    ]
