# Generated by Django 3.2.9 on 2021-12-17 12:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Subscrap', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sublist',
            name='startDate',
            field=models.DateField(default=datetime.datetime(2021, 12, 17, 12, 34, 26, 474120)),
        ),
    ]
